# -*- coding: utf-8 -*-
"""Problem_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j9djU3r70AgvUe_SIYkwgVR60hmsiviZ
"""

def read():
    file=open("input3.txt", "r")
    arr=[]
    for l in file:
        arr.append(l.split())
    for i in range(len(arr[2])):
        arr[2][i]=int(arr[2][i])
    input1=arr[1]
    num=arr[2]
    file.close()
    file=open("input3.txt","r")
    arr=[]
    for line in file:
        arr.append(l.split())
    for i in range(len(arr[2])):
        arr[2][i]=int(arr[2][i])
    input2= arr[1]
    var= arr[2]
    file.close()
    return input1,num,input2,var

def write(input1,input2):
    file=open("output3.txt","w")
    file.write(str(input1))
    file=open("altoutput3.txt","w")
    file.write(str(input2))

def insertionSorting(new):
    for i in range(0,len(new)-1):
        flag=new[i+1]
        j=i
        while (j>=0):
            if new[j]<flag:
                new[j+1]=new[j]
            else:
                break
            j=j-1
        new[j+1]=flag
input1,num,input2,var= read()
dictio={}
sorted_input1= []
for i in range(len(num)):
    if num[i] in dictio:
        dictio[num[i]].append(input1[i])
    else:
        dictio[num[i]]=[input1[i]]
insertionSorting(num)
for j in num:
    for input1 in dictio[j]:
        if input1 not in sorted_input1:
            sorted_input1.append(input1)
for i in range(len(sorted_input1)):
    print(sorted_input1[i],end=" ")
print()
dictio={}
sorted_input2=[]
for i in range(len(var)):
    if var[i] in dictio:
        dictio[var[i]].append(input2[i])
    else:
        dictio[var[i]]=[input2[i]]
insertionSorting(var)
for j in var:
    for input2 in dictio[j]:
        if input2 not in sorted_input2:
            sorted_input2.append(input2)
for i in range(len(sorted_input2)):
    print(sorted_input2[i],end=" ")
write(sorted_input1,sorted_input2)