# -*- coding: utf-8 -*-
"""Problem_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EWNKqA3hckNM1SiVpOESTfD6OH49pFDL
"""

def read():
    file=open("input4.txt","r")
    lists=[]
    for l in file:
        lists.append(l.split())
    for i in range(len(lists[1])):
        lists[1][i]=int(lists[1][i])
    var=lists[1]
    file.close()
    file= open("alt_input4.txt","r")
    lists=[]
    for l in file:
        lists.append(l.split())
    for i in range(len(lists[1])):
        lists[1][i]=int(lists[1][i])
    value=lists[1]
    file.close()
    return var,value


def write(var,value):
    file= open("output4.txt","w")
    file.write(str(var))
    file= open("alt_output4.txt","w")
    file.write(str(value))


def merge(a,b,c,s):
    num=c-b+1
    here=s-c
    left = [0]*num
    right = [0]*here
    for i in range(0,num):
        left[i] =a[b+i]
    for j in range(0,here):
        right[j]=a[c+1+j]
    count= 0
    j = 0
    k =b
    while count<num and j<here:
        if left[count]<= right[j]:
            a[k]= left[count]
            count+= 1
        else:
            a[k]= right[j]
            j += 1
        k += 1
    while count<num:
        a[k] =left[count]
        count+= 1
        k += 1
    while j<here:
        a[k] = right[j]
        j+= 1
        k+= 1
def merge_sort(a,b,s):
    if b<s:
        c=b+(s-b)//2
        merge_sort(a,b,c)
        merge_sort(a,c+1,s)
        merge(a,b,c,s)
var,value=read()
merge_sort(var,0,len(var)- 1)
merge_sort(value,0,len(value)- 1)
print(var)
print(value)
write(var,value)