# -*- coding: utf-8 -*-
"""Problem_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t3QY2mvyuOdGtRCCAz0jWTGVUDeDZw8R
"""

#Task-01

def read():
    file=open("Problem01_input1.txt","r")
    arr=[]
    for line in file:
        arr.append(line.split())
    for index in range(len(arr[1])):
        arr[1][index]=int(arr[1][index])
    here=arr[1]
    file.close()
    return here
def write(here):
    file=open("Problem01_output1.txt","w")
    file.write(str(here))
def bubbleSort(arr):
    for index in range(len(arr)-1):
        flag=False
        for index_2 in range(len(arr)-index-1):
            if (arr[index_2]>arr[index_2+1]):
                flag=True
                num=arr[index_2]
                arr[index_2]=arr[index_2+1]
                arr[index_2+1]=num
        if flag==False:
            break
    return arr
here=read()
bubbleSort(here)
write(here)